macos

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -78,67 +78,52 @@ jobs:
   build_macos:
     runs-on: macos-latest
     permissions: write-all
-
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v3
-        with:
-          submodules: true
-
-      - name: Install Dependencies
-        run: brew install boost
-
-      - name: List Files for debugging purposes
-        run: |
-          ls -R
-
-      - name: Clean Build Directory
-        run: rm -rf build
-
-      - name: Download Boost 1.86.0
-        run: |
-          wget https://boostorg.jfrog.io/artifactory/main/release/1.86.0/source/boost_1_86_0.tar.bz2
-          tar -xvjf boost_1_86_0.tar.bz2
-          mv boost_1_86_0 boost
-
-      - name: Build Boost Verbosely
-        run: |
-          cd boost
-          ./bootstrap.sh --with-libraries=program_options,system,filesystem --prefix=$HOME/boost
-          ./b2 install --verbose
-          cd ..
-
-      - name: Configure CMake with Local Boost
-        run: |
-          cmake -S . -B build -DPATCH_VERSION=${{ github.run_number }} -DBOOST_ROOT=./boost/install -DCMAKE_CXX_FLAGS="-std=c++17" --no-warn-unused-cli
-
-      - name: Build Project
-        run: cmake --build build --verbose
-
-      - name: Package Project
-        run: cmake --build build --target package --verbose
-
-      - name: List Files in Build Directory
-        run: ls -R build
-
-      - name: Create Release
-        id: create_release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          tag_name: v${{ github.run_number }}
-          release_name: Release ${{ github.run_number }} (macOS)
-          draft: false
-          prerelease: false
-
-      - name: Upload Release Asset
-        id: upload-release-asset-macos
-        uses: actions/upload-release-asset@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          upload_url: ${{ steps.create_release.outputs.upload_url }}
-          asset_path: ./build/boboost-0.0.${{ github.run_number }}-macos.deb # Adjust the asset path if necessary
-          asset_name: boboost-0.0.${{ github.run_number }}-macos.deb # Adjust the asset name if necessary
-          asset_content_type: application/vnd.debian.binary-package # Change this to the appropriate content type for macOS, e.g., application/octet-stream if necessary.
+    - uses: actions/checkout@v3
+      with:
+        submodules: true
+    - name: Download Boost 1.86.0
+      run: |
+        wget https://boostorg.jfrog.io/artifactory/main/release/1.86.0/source/boost_1_86_0.tar.bz2
+        tar -xvjf boost_1_86_0.tar.bz2
+        mv boost_1_86_0 boost
+    - name: Build Boost
+      run: |
+        cd boost
+        ./bootstrap.sh --with-libraries=program_options,system,filesystem
+        ./b2 install --prefix=$(pwd)/boost/install
+        cd ..
+    - name: Configure CMake with Local Boost
+      run: |
+        cmake -S . -B build -DPATCH_VERSION=${{ github.run_number }} -DBOOST_ROOT=$(pwd)/boost/install -DCMAKE_CXX_FLAGS="-std=c++17"
+    - name: Build Project
+      run: cmake --build build --verbose
+    - name: Create Package (ZIP)
+      run: cpack -G ZIP
+    - name: Run Tests (If Applicable)
+      run: |
+        ctest --output-on-failure
+        if [ $? -ne 0 ]; then
+          echo "Tests failed!"
+          exit 1
+        fi
+    - name: Create Release (MacOS)
+      id: create_release_macos
+      uses: actions/create-release@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        tag_name: ${{ github.run_number }}
+        release_name: Release ${{ github.run_number }} (MacOS)
+        draft: false
+        prerelease: false
+    - name: Upload Release Asset (MacOS)
+      id: upload-release-asset-macos
+      uses: actions/upload-release-asset@v1
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      with:
+        upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
+        asset_path: ./boboost-0.0.${{ github.run_number }}-Darwin.zip
+        asset_name: boboost-0.0.${{ github.run_number }}-Darwin.zip
+        asset_content_type: application/zip
